services:
  frontend_app:
    image: node:latest
    container_name: VT6003CEM_frontend_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - type: bind
        source: ./code
        target: /app
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - TZ=UTC
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: > 
      sh -c "
        npm install &&
        npm start
      "